In [13]:
import pandas as pd

# Read the CSV files
df1 = pd.read_csv('Data/Infected_test_post_ML_New.csv')
df2 = pd.read_csv('Data/Unifected_test_post_ML_New.csv')

In [14]:
df1

,Unnamed: 0,ImageFileName,Target,Predictions
0,0,C131P92ThinF_IMG_20151004_151001_cell_119.png,1,1
1,1,C131P92ThinF_IMG_20151004_151001_cell_120.png,1,1
2,2,C131P92ThinF_IMG_20151004_151001_cell_121.png,1,1
3,3,C131P92ThinF_IMG_20151004_151001_cell_123.png,1,1
4,4,C131P92ThinF_IMG_20151004_151001_cell_126.png,1,1
...,...,...,...,...
745,745,C136P97ThinF_IMG_20151005_141946_cell_104.png,1,1
746,746,C136P97ThinF_IMG_20151005_141946_cell_105.png,1,1
747,747,C136P97ThinF_IMG_20151005_141946_cell_106.png,1,1
748,748,C136P97ThinF_IMG_20151005_141946_cell_107.png,1,1
749,749,C136P97ThinF_IMG_20151005_141946_cell_108.png,1,1

In [15]:
df2

,Unnamed: 0,ImageFileName,Target,Predictions
0,0,C137P98ThinF_IMG_20151005_160256_cell_35.png,0,0
1,1,C137P98ThinF_IMG_20151005_160256_cell_45.png,0,0
2,2,C137P98ThinF_IMG_20151005_160918_cell_21.png,0,0
3,3,C137P98ThinF_IMG_20151005_160918_cell_22.png,0,0
4,4,C137P98ThinF_IMG_20151005_160918_cell_42.png,0,0
...,...,...,...,...
745,745,C152P113ThinF_IMG_20151115_124032_cell_90.png,0,0
746,746,C152P113ThinF_IMG_20151115_124217_cell_103.png,0,0
747,747,C152P113ThinF_IMG_20151115_124217_cell_106.png,0,0
748,748,C152P113ThinF_IMG_20151115_124217_cell_118.png,0,0
749,749,C152P113ThinF_IMG_20151115_124217_cell_145.png,0,0

In [16]:
df1 = df1[["ImageFileName", "Target","Predictions"]]

In [17]:
df1

                                     ImageFileName  Target  Predictions
0    C131P92ThinF_IMG_20151004_151001_cell_119.png       1            1
1    C131P92ThinF_IMG_20151004_151001_cell_120.png       1            1
2    C131P92ThinF_IMG_20151004_151001_cell_121.png       1            1
3    C131P92ThinF_IMG_20151004_151001_cell_123.png       1            1
4    C131P92ThinF_IMG_20151004_151001_cell_126.png       1            1
..                                             ...     ...          ...
745  C136P97ThinF_IMG_20151005_141946_cell_104.png       1            1
746  C136P97ThinF_IMG_20151005_141946_cell_105.png       1            1
747  C136P97ThinF_IMG_20151005_141946_cell_106.png       1            1
748  C136P97ThinF_IMG_20151005_141946_cell_107.png       1            1
749  C136P97ThinF_IMG_20151005_141946_cell_108.png       1            1

[750 rows x 3 columns]

In [18]:
df2 = df2[["ImageFileName", "Target","Predictions"]]

In [19]:
df2

                                      ImageFileName  Target  Predictions
0      C137P98ThinF_IMG_20151005_160256_cell_35.png       0            0
1      C137P98ThinF_IMG_20151005_160256_cell_45.png       0            0
2      C137P98ThinF_IMG_20151005_160918_cell_21.png       0            0
3      C137P98ThinF_IMG_20151005_160918_cell_22.png       0            0
4      C137P98ThinF_IMG_20151005_160918_cell_42.png       0            0
..                                              ...     ...          ...
745   C152P113ThinF_IMG_20151115_124032_cell_90.png       0            0
746  C152P113ThinF_IMG_20151115_124217_cell_103.png       0            0
747  C152P113ThinF_IMG_20151115_124217_cell_106.png       0            0
748  C152P113ThinF_IMG_20151115_124217_cell_118.png       0            0
749  C152P113ThinF_IMG_20151115_124217_cell_145.png       0            0

[750 rows x 3 columns]

In [20]:
c = df1.append(df2)

C:\Users\Randg\AppData\Local\Temp\ipykernel_39960\2278186009.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  c = df1.append(df2)

In [21]:
c

                                      ImageFileName  Target  Predictions
0     C131P92ThinF_IMG_20151004_151001_cell_119.png       1            1
1     C131P92ThinF_IMG_20151004_151001_cell_120.png       1            1
2     C131P92ThinF_IMG_20151004_151001_cell_121.png       1            1
3     C131P92ThinF_IMG_20151004_151001_cell_123.png       1            1
4     C131P92ThinF_IMG_20151004_151001_cell_126.png       1            1
..                                              ...     ...          ...
745   C152P113ThinF_IMG_20151115_124032_cell_90.png       0            0
746  C152P113ThinF_IMG_20151115_124217_cell_103.png       0            0
747  C152P113ThinF_IMG_20151115_124217_cell_106.png       0            0
748  C152P113ThinF_IMG_20151115_124217_cell_118.png       0            0
749  C152P113ThinF_IMG_20151115_124217_cell_145.png       0            0

[1500 rows x 3 columns]

In [22]:
# Save combined data to a new CSV file
c.to_csv('Data/combined_test_New.csv',  index=False)